# Generated by Django 4.2.15 on 2026-07-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeatherBraceletBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slot_count', models.PositiveIntegerField()),
                ('cord_image', models.ImageField(blank=True, help_text='Not used by the live builder. Reserved for a future checkout-time composite image.', null=True, upload_to='leather_bracelet_bases/')),
            ],
            options={
                'ordering': ['size', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='braceletconfiguration',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='configurator.braceletbase'),
        ),
        migrations.AddField(
            model_name='braceletconfiguration',
            name='leather_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='configurator.leatherbraceletbase'),
        ),
    ]
