# Generated by Django 4.2.15 on 2026-07-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeatherBraceletBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slot_count', models.PositiveIntegerField()),
                ('cord_image', models.ImageField(upload_to='leather_bracelet_bases/')),
                ('beaded_segment_offset_pct', models.DecimalField(decimal_places=2, help_text="Distance from cord_image's left edge to the start of the beaded segment, as a % of image width.", max_digits=5)),
                ('beaded_segment_width_pct', models.DecimalField(decimal_places=2, help_text='Width of the beaded segment within cord_image, as a % of image width.', max_digits=5)),
            ],
            options={
                'ordering': ['size', 'name'],
            },
        ),
        migrations.AddField(
            model_name='braceletbase',
            name='material',
            field=models.CharField(choices=[('elastic_silicone', 'Elastic Silicone'), ('metal_chain', 'Metal Chain'), ('fabric_cord', 'Fabric Cord')], default='elastic_silicone', max_length=20),
        ),
        migrations.AlterField(
            model_name='braceletconfiguration',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='configurator.braceletbase'),
        ),
        migrations.AddField(
            model_name='braceletconfiguration',
            name='leather_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='configurator.leatherbraceletbase'),
        ),
    ]
