# Generated by Django 4.2.15 on 2026-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_remove_leatherbraceletbase_beaded_segment_offset_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leatherbraceletbase',
            name='bead_orbit_radius_pct',
            field=models.DecimalField(decimal_places=2, default=27, help_text="Bead orbit radius as a % of cord_image's shorter dimension (its height, typically).", max_digits=5),
        ),
        migrations.AlterField(
            model_name='leatherbraceletbase',
            name='beaded_arc_end_deg',
            field=models.DecimalField(decimal_places=1, default=325, help_text='Arc end angle, same convention as beaded_arc_start_deg.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leatherbraceletbase',
            name='beaded_arc_start_deg',
            field=models.DecimalField(decimal_places=1, default=215, help_text="Arc start angle: 0deg = 3 o'clock, increasing counter-clockwise (90deg = 12 o'clock, 270deg = 6 o'clock).", max_digits=5),
        ),
    ]
