# Generated by Django 4.2.15 on 2026-07-16 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ('-created_at', 'currency_code'),
                'unique_together': {('currency_code', 'created_at')},
            },
        ),
    ]
