"""
Django settings for bracelet_builder project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from celery.schedules import crontab
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)y5z*8-+#xu0-*-40v(%egy7cnw*b#rj7de*$+c%n^l_q)vq2*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'aside-pseudonarcotic-rosette.ngrok-free.dev']
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',') if config('CSRF_TRUSTED_ORIGINS', default='') else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'configurator',
    'checkout',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bracelet_builder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bracelet_builder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "bracelet_builder_db",
        "USER": "postgres",
        "PASSWORD": "Fandango_1",
        "HOST": "localhost",
        "PORT": "5432",
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded item images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Celery
# https://docs.celeryq.dev/en/stable/userguide/configuration.html
#
# CELERY_BROKER_URL points at this project's own RabbitMQ vhost
# ("/bracelet_builder"), not the default "/" vhost — kept separate from
# other projects (e.g. Vadevia) that may share the same RabbitMQ instance.
# CELERY_TASK_DEFAULT_QUEUE is set explicitly (rather than relying on
# Celery's generic "celery" default queue name) as defense in depth on top
# of the vhost isolation, in case a vhost is ever misconfigured to be
# shared later. The task itself is also namespaced
# ("bracelet_builder.send_order_confirmation_email") for the same reason.

CELERY_BROKER_URL = config(
    'CELERY_BROKER_URL', default='amqp://guest:guest@localhost:5672/bracelet_builder'
)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=None)
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_DEFAULT_QUEUE = 'bracelet_builder'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Runs once a day — update_currency_rates itself is idempotent per-day (see
# CurrencyExchangeRate's unique_together), so a missed/duplicate beat tick
# just no-ops instead of double-writing today's rate.
CELERY_BEAT_SCHEDULE = {
    'update-currency-rates-daily': {
        'task': 'bracelet_builder.update_currency_rates',
        'schedule': crontab(hour=3, minute=0),
    },
}


# Email
# https://docs.djangoproject.com/en/4.2/topics/email/

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@bracelet-builder.local')

# ADMINS is a comma-separated list of email addresses (e.g.
# "admin@example.com,ops@example.com") — blank/unset by default so the
# project still runs with no admin-notification recipients configured.
# NOTE: this is a plain list of email strings, not Django's usual list of
# (name, email) tuples. Fine while DEBUG=True (Django's built-in 500-error
# mailer, the thing that actually requires the tuple shape, is inactive in
# debug mode) — if DEBUG is ever set False and that mailer is needed, this
# will need to go back to parsing "name:email" pairs into tuples.
ADMINS = config(
    'ADMINS', default='',
    cast=lambda v: [email.strip() for email in v.split(',') if email.strip()],
)


# Site URL (used to build absolute URLs for gateway back-urls/webhooks)

PROTOCOL = config('SITE_PROTOCOL', default='http://')
DOMAIN = config('SITE_DOMAIN', default='localhost:8000')


# Payment gateways — dev/test placeholders, replace with real credentials per environment.

STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_API_BASE_URL = config('PAYPAL_API_BASE_URL', default='https://api-m.sandbox.paypal.com')
# ID of the webhook registered in the PayPal Developer Dashboard for this
# app's client ID — required to verify incoming webhook payloads via
# PayPal's verify-webhook-signature API (see payment/paypal_client.py).
PAYPAL_WEBHOOK_ID = config('PAYPAL_WEBHOOK_ID', default='')

MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='')
MERCADOPAGO_PUBLIC_KEY = config('MERCADOPAGO_PUBLIC_KEY', default='')
